package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/vishnujayvel/hookwise/internal/core"
)

// defaultYAMLTemplate is the minimal hookwise.yaml created by `hookwise init`.
const defaultYAMLTemplate = `# hookwise.yaml -- generated by hookwise init
# Docs: https://github.com/hookwise/hookwise
version: 1

guards: []

analytics:
  enabled: true

status_line:
  enabled: false

tui:
  auto_launch: false
  launch_method: "newWindow"

# feeds:
#   weather:
#     enabled: true
#     interval_seconds: 900
#     latitude: 37.7749
#     longitude: -122.4194
#     temperature_unit: "fahrenheit" # or "celsius"
`

func newInitCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Initialize hookwise configuration",
		Long:  "Creates a default hookwise.yaml in the current directory and ensures the ~/.hookwise/ state directory exists.",
		RunE:  runInit,
	}
}

func runInit(cmd *cobra.Command, args []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("could not determine working directory: %w", err)
	}

	configPath := filepath.Join(cwd, core.ProjectConfigFile)

	// Check if hookwise.yaml already exists.
	if _, err := os.Stat(configPath); err == nil {
		fmt.Fprintf(cmd.OutOrStdout(), "hookwise.yaml already exists at %s -- skipping.\n", configPath)
		return nil
	}

	// Write default config.
	if err := os.WriteFile(configPath, []byte(defaultYAMLTemplate), 0o644); err != nil {
		return fmt.Errorf("failed to write %s: %w", configPath, err)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "Created %s\n", configPath)

	// Ensure state directory exists.
	stateDir := core.GetStateDir()
	if err := core.EnsureDir(stateDir, core.DefaultDirMode); err != nil {
		return fmt.Errorf("failed to create state directory %s: %w", stateDir, err)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "Ensured state directory %s\n", stateDir)

	fmt.Fprintln(cmd.OutOrStdout(), "hookwise initialized successfully.")
	return nil
}
