package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/vishnujayvel/hookwise/internal/analytics"
	"github.com/vishnujayvel/hookwise/internal/core"
	"github.com/vishnujayvel/hookwise/internal/migration"
	"github.com/vishnujayvel/hookwise/internal/notifications"
	"gopkg.in/yaml.v3"
)

// Injected at build time via -ldflags.
var (
	version   = "dev"
	commit    = "none"
	buildDate = "unknown"
)

func main() {
	rootCmd := newRootCmd()

	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}

// newRootCmd creates the root command with all subcommands attached.
// Extracted from main() so tests can invoke commands without exec-ing a binary.
func newRootCmd() *cobra.Command {
	rootCmd := &cobra.Command{
		Use:     "hookwise",
		Short:   "Config-driven hook framework for Claude Code",
		Long:    "Hookwise provides guards, analytics, coaching, feeds, and an interactive TUI for Claude Code sessions.",
		Version: fmt.Sprintf("%s (commit: %s, built: %s)", version, commit, buildDate),
	}

	rootCmd.AddCommand(
		newDispatchCmd(),
		newInitCmd(),
		newDoctorCmd(),
		newStatsCmd(),
		newDiffCmd(),
		newLogCmd(),
		newStatusLineCmd(),
		newTestCmd(),
		newUpgradeCmd(),
		newNotificationsCmd(),
	)

	return rootCmd
}

// newDispatchCmd handles "hookwise dispatch <EventType>".
// Reads JSON from stdin, runs the three-phase dispatch pipeline, writes result to stdout.
func newDispatchCmd() *cobra.Command {
	var projectDir string

	cmd := &cobra.Command{
		Use:   "dispatch <EventType>",
		Short: "Dispatch a hook event (called by Claude Code)",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			eventType := args[0]

			result := core.SafeDispatch(func() core.DispatchResult {
				// Read payload from stdin
				payload := core.ReadStdinPayload()

				// Resolve project directory
				dir := projectDir
				if dir == "" {
					var err error
					dir, err = os.Getwd()
					if err != nil {
						dir = "."
					}
				}

				// Load config
				config, err := core.LoadConfig(dir)
				if err != nil {
					core.Logger().Error("failed to load config", "error", err)
					// Malformed config -> exit 0 silently (fail-open)
					return core.DispatchResult{ExitCode: 0}
				}

				// Run the three-phase dispatch engine
				return core.Dispatch(eventType, payload, config)
			})

			if result.Stdout != nil {
				fmt.Print(*result.Stdout)
			}
			os.Exit(result.ExitCode)
			return nil
		},
	}

	cmd.Flags().StringVar(&projectDir, "project-dir", "", "Project directory (defaults to cwd)")

	return cmd
}

// ---------------------------------------------------------------------------
// init command (R7.1)
// ---------------------------------------------------------------------------

// defaultYAMLTemplate is the minimal hookwise.yaml created by `hookwise init`.
const defaultYAMLTemplate = `# hookwise.yaml -- generated by hookwise init
# Docs: https://github.com/hookwise/hookwise
version: 1

guards: []

analytics:
  enabled: true

status_line:
  enabled: false

tui:
  auto_launch: false
  launch_method: "newWindow"
`

func newInitCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Initialize hookwise configuration",
		Long:  "Creates a default hookwise.yaml in the current directory and ensures the ~/.hookwise/ state directory exists.",
		RunE:  runInit,
	}
}

func runInit(cmd *cobra.Command, args []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("could not determine working directory: %w", err)
	}

	configPath := filepath.Join(cwd, core.ProjectConfigFile)

	// Check if hookwise.yaml already exists.
	if _, err := os.Stat(configPath); err == nil {
		fmt.Fprintf(cmd.OutOrStdout(), "hookwise.yaml already exists at %s -- skipping.\n", configPath)
		return nil
	}

	// Write default config.
	if err := os.WriteFile(configPath, []byte(defaultYAMLTemplate), 0o644); err != nil {
		return fmt.Errorf("failed to write %s: %w", configPath, err)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "Created %s\n", configPath)

	// Ensure state directory exists.
	stateDir := core.GetStateDir()
	if err := core.EnsureDir(stateDir, core.DefaultDirMode); err != nil {
		return fmt.Errorf("failed to create state directory %s: %w", stateDir, err)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "Ensured state directory %s\n", stateDir)

	fmt.Fprintln(cmd.OutOrStdout(), "hookwise initialized successfully.")
	return nil
}

// ---------------------------------------------------------------------------
// doctor command (R7.2)
// ---------------------------------------------------------------------------

func newDoctorCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "doctor",
		Short: "Run system health checks",
		Long:  "Checks hookwise.yaml validity, Dolt DB connectivity, state directory, and daemon status.",
		RunE:  runDoctor,
	}
}

func runDoctor(cmd *cobra.Command, args []string) error {
	w := cmd.OutOrStdout()
	fmt.Fprintln(w, "hookwise doctor")
	fmt.Fprintln(w, strings.Repeat("-", 40))

	allOK := true

	// Check 1: hookwise.yaml exists and is valid.
	cwd, _ := os.Getwd()
	configPath := filepath.Join(cwd, core.ProjectConfigFile)
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		fmt.Fprintf(w, "FAIL  config: %s not found\n", core.ProjectConfigFile)
		allOK = false
	} else {
		// Try to load and validate.
		data, readErr := os.ReadFile(configPath)
		if readErr != nil {
			fmt.Fprintf(w, "FAIL  config: cannot read %s: %v\n", configPath, readErr)
			allOK = false
		} else {
			var raw map[string]interface{}
			if parseErr := yaml.Unmarshal(data, &raw); parseErr != nil {
				fmt.Fprintf(w, "FAIL  config: invalid YAML: %v\n", parseErr)
				allOK = false
			} else {
				vr := core.ValidateConfig(raw)
				if vr.Valid {
					fmt.Fprintln(w, "PASS  config: hookwise.yaml is valid")
				} else {
					fmt.Fprintf(w, "WARN  config: %d validation issue(s)\n", len(vr.Errors))
					for _, e := range vr.Errors {
						fmt.Fprintf(w, "       - %s: %s\n", e.Path, e.Message)
					}
					// Warnings don't fail doctor outright.
				}
			}
		}
	}

	// Check 2: State directory.
	stateDir := core.GetStateDir()
	if info, err := os.Stat(stateDir); err != nil || !info.IsDir() {
		fmt.Fprintf(w, "FAIL  state-dir: %s does not exist\n", stateDir)
		allOK = false
	} else {
		fmt.Fprintf(w, "PASS  state-dir: %s\n", stateDir)
	}

	// Check 3: Dolt DB.
	doltDir := analytics.DefaultDoltDir()
	if info, err := os.Stat(doltDir); err != nil || !info.IsDir() {
		fmt.Fprintf(w, "WARN  dolt-db: %s not found (will be created on first dispatch)\n", doltDir)
	} else {
		fmt.Fprintf(w, "PASS  dolt-db: %s\n", doltDir)
	}

	// Check 4: Daemon PID file.
	pidPath := core.DefaultPIDPath
	if _, err := os.Stat(pidPath); os.IsNotExist(err) {
		fmt.Fprintln(w, "INFO  daemon: no PID file (daemon not running)")
	} else {
		pidData, err := os.ReadFile(pidPath)
		if err == nil {
			fmt.Fprintf(w, "PASS  daemon: PID file exists (pid: %s)\n", strings.TrimSpace(string(pidData)))
		} else {
			fmt.Fprintf(w, "WARN  daemon: PID file exists but unreadable: %v\n", err)
		}
	}

	fmt.Fprintln(w, strings.Repeat("-", 40))
	if allOK {
		fmt.Fprintln(w, "All critical checks passed.")
	} else {
		fmt.Fprintln(w, "Some checks failed. Run 'hookwise init' to fix.")
	}

	return nil
}

// ---------------------------------------------------------------------------
// status-line command (R7.3)
// ---------------------------------------------------------------------------

// ANSI color helpers.
const (
	ansiReset  = "\033[0m"
	ansiBold   = "\033[1m"
	ansiGreen  = "\033[32m"
	ansiYellow = "\033[33m"
	ansiCyan   = "\033[36m"
	ansiGray   = "\033[90m"
)

func newStatusLineCmd() *cobra.Command {
	var projectDir string

	cmd := &cobra.Command{
		Use:   "status-line",
		Short: "Render the status line",
		Long:  "Loads config and feed cache, then renders a single ANSI-colored status line to stdout.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runStatusLine(cmd, projectDir)
		},
	}

	cmd.Flags().StringVar(&projectDir, "project-dir", "", "Project directory (defaults to cwd)")
	return cmd
}

func runStatusLine(cmd *cobra.Command, projectDir string) error {
	if projectDir == "" {
		var err error
		projectDir, err = os.Getwd()
		if err != nil {
			projectDir = "."
		}
	}

	config, err := core.LoadConfig(projectDir)
	if err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	if !config.StatusLine.Enabled {
		fmt.Fprintln(cmd.OutOrStdout(), ansiGray+"(status line disabled)"+ansiReset)
		return nil
	}

	delimiter := config.StatusLine.Delimiter
	if delimiter == "" {
		delimiter = core.DefaultStatusDelimiter
	}

	var segments []string

	for _, seg := range config.StatusLine.Segments {
		rendered := renderSegment(seg)
		if rendered != "" {
			segments = append(segments, rendered)
		}
	}

	if len(segments) == 0 {
		segments = append(segments, ansiGreen+"hookwise"+ansiReset)
	}

	// Surface unsurfaced notifications (R12.5).
	notifSegment := renderNotificationSegment()
	if notifSegment != "" {
		segments = append(segments, notifSegment)
	}

	line := strings.Join(segments, ansiGray+delimiter+ansiReset)
	fmt.Fprintln(cmd.OutOrStdout(), line)
	return nil
}

// renderNotificationSegment queries the Dolt DB for unsurfaced notifications
// and returns a status-line segment summarising them. If the DB cannot be
// opened or there are no pending notifications, returns "".
func renderNotificationSegment() string {
	db, err := analytics.Open("")
	if err != nil {
		return ""
	}
	defer db.Close()

	ctx := context.Background()
	ns := notifications.NewNotificationService(db)

	unsurfaced, err := ns.Unsurfaced(ctx)
	if err != nil || len(unsurfaced) == 0 {
		return ""
	}

	// Show count and the most recent notification's content (truncated).
	latest := unsurfaced[len(unsurfaced)-1]
	content := latest.Content
	if len(content) > 40 {
		content = content[:37] + "..."
	}

	segment := fmt.Sprintf("%s%d notif%s%s %s%s%s",
		ansiYellow, len(unsurfaced), pluralS(len(unsurfaced)), ansiReset,
		ansiGray, content, ansiReset)

	// Mark them as surfaced.
	for _, n := range unsurfaced {
		_ = ns.MarkSurfaced(ctx, n.ID)
	}

	return segment
}

// pluralS returns "s" when count != 1, "" otherwise.
func pluralS(count int) string {
	if count == 1 {
		return ""
	}
	return "s"
}

// renderSegment renders a single status-line segment with ANSI colors.
func renderSegment(seg core.SegmentConfig) string {
	if seg.Builtin != "" {
		return renderBuiltinSegment(seg.Builtin)
	}
	if seg.Custom != nil && seg.Custom.Command != "" {
		label := seg.Custom.Label
		if label == "" {
			label = "custom"
		}
		return ansiCyan + label + ansiReset
	}
	return ""
}

// renderBuiltinSegment renders a known builtin segment by name.
func renderBuiltinSegment(name string) string {
	switch name {
	case "session":
		return ansiBold + ansiGreen + "session" + ansiReset
	case "cost":
		return ansiYellow + "cost: $0.00" + ansiReset
	case "project":
		return ansiCyan + "project" + ansiReset
	case "calendar":
		return ansiCyan + "calendar" + ansiReset
	case "pulse":
		return ansiGreen + "pulse" + ansiReset
	case "weather":
		return ansiCyan + "weather" + ansiReset
	default:
		return ansiGray + name + ansiReset
	}
}

// ---------------------------------------------------------------------------
// test command (R7.4) -- guard test runner
// ---------------------------------------------------------------------------

func newTestCmd() *cobra.Command {
	var projectDir string

	cmd := &cobra.Command{
		Use:   "test",
		Short: "Evaluate guard test scenarios",
		Long:  "Loads config, creates synthetic test payloads for each guard rule, evaluates them, and reports pass/fail.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runTest(cmd, projectDir)
		},
	}

	cmd.Flags().StringVar(&projectDir, "project-dir", "", "Project directory (defaults to cwd)")
	return cmd
}

func runTest(cmd *cobra.Command, projectDir string) error {
	if projectDir == "" {
		var err error
		projectDir, err = os.Getwd()
		if err != nil {
			projectDir = "."
		}
	}

	config, err := core.LoadConfig(projectDir)
	if err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	w := cmd.OutOrStdout()
	fmt.Fprintln(w, "hookwise test -- guard rule evaluation")
	fmt.Fprintln(w, strings.Repeat("-", 40))

	if len(config.Guards) == 0 {
		fmt.Fprintln(w, "No guard rules defined. Nothing to test.")
		return nil
	}

	passed := 0
	failed := 0

	for i, rule := range config.Guards {
		// Create a synthetic payload that should trigger this rule.
		payload := buildTestPayload(rule)
		result := core.Evaluate(rule.Match, payload, config.Guards)

		// The rule should match and produce its expected action.
		expectAction := rule.Action
		actualAction := result.Action

		if actualAction == expectAction {
			fmt.Fprintf(w, "PASS  [%d] match=%q action=%s\n", i+1, rule.Match, actualAction)
			passed++
		} else {
			fmt.Fprintf(w, "FAIL  [%d] match=%q expected=%s got=%s\n", i+1, rule.Match, expectAction, actualAction)
			failed++
		}
	}

	fmt.Fprintln(w, strings.Repeat("-", 40))
	fmt.Fprintf(w, "Results: %d passed, %d failed, %d total\n", passed, failed, passed+failed)

	if failed > 0 {
		return fmt.Errorf("%d guard test(s) failed", failed)
	}
	return nil
}

// buildTestPayload creates a synthetic payload designed to trigger the given rule.
// If the rule has a "when" condition, we try to populate the payload so the condition is satisfied.
func buildTestPayload(rule core.GuardRuleConfig) map[string]interface{} {
	payload := map[string]interface{}{
		"session_id": "test-session",
		"tool_name":  rule.Match,
	}

	// Parse the "when" condition to build a payload that satisfies it.
	if rule.When != "" {
		parsed := core.ParseCondition(rule.When)
		if parsed != nil {
			setNestedField(payload, parsed.FieldPath, buildMatchValue(parsed))
		}
	}

	return payload
}

// setNestedField sets a value at a dot-separated path in a map.
func setNestedField(m map[string]interface{}, path string, value interface{}) {
	parts := strings.Split(path, ".")
	current := m
	for i := 0; i < len(parts)-1; i++ {
		child, ok := current[parts[i]].(map[string]interface{})
		if !ok {
			child = make(map[string]interface{})
			current[parts[i]] = child
		}
		current = child
	}
	current[parts[len(parts)-1]] = value
}

// buildMatchValue creates a string value that satisfies the given parsed condition.
func buildMatchValue(cond *core.ParsedCondition) string {
	switch cond.Operator {
	case "contains":
		return "prefix_" + cond.Value + "_suffix"
	case "starts_with":
		return cond.Value + "_rest"
	case "ends_with":
		return "start_" + cond.Value
	case "==", "equals":
		return cond.Value
	case "matches":
		return cond.Value // best effort: use the regex pattern as a literal
	default:
		return cond.Value
	}
}

// ---------------------------------------------------------------------------
// stats command (R7.5)
// ---------------------------------------------------------------------------

func newStatsCmd() *cobra.Command {
	var dataDir string

	cmd := &cobra.Command{
		Use:   "stats",
		Short: "Show analytics dashboard for today",
		Long:  "Opens the Dolt database and displays today's daily summary and tool breakdown.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runStats(cmd, dataDir)
		},
	}

	cmd.Flags().StringVar(&dataDir, "data-dir", "", "Dolt data directory (defaults to ~/.hookwise/dolt)")
	return cmd
}

func runStats(cmd *cobra.Command, dataDir string) error {
	db, err := analytics.Open(dataDir)
	if err != nil {
		return fmt.Errorf("failed to open Dolt DB: %w", err)
	}
	defer db.Close()

	ctx := context.Background()
	today := time.Now().Format("2006-01-02")
	a := analytics.NewAnalytics(db)

	w := cmd.OutOrStdout()
	fmt.Fprintf(w, "hookwise stats -- %s\n", today)
	fmt.Fprintln(w, strings.Repeat("-", 40))

	// Daily summary.
	summary, err := a.DailySummary(ctx, today)
	if err != nil {
		return fmt.Errorf("daily summary: %w", err)
	}

	fmt.Fprintf(w, "Sessions:       %d\n", summary.TotalSessions)
	fmt.Fprintf(w, "Events:         %d\n", summary.TotalEvents)
	fmt.Fprintf(w, "Tool calls:     %d\n", summary.TotalToolCalls)
	fmt.Fprintf(w, "File edits:     %d\n", summary.TotalFileEdits)
	fmt.Fprintf(w, "AI lines:       %d\n", summary.AIAuthoredLines)
	fmt.Fprintf(w, "Human lines:    %d\n", summary.HumanVerifiedLines)
	fmt.Fprintf(w, "Est. cost:      $%.2f\n", summary.EstimatedCostUSD)

	// Tool breakdown.
	breakdown, err := a.ToolBreakdown(ctx, today)
	if err != nil {
		return fmt.Errorf("tool breakdown: %w", err)
	}

	if len(breakdown) > 0 {
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Tool breakdown:")
		for _, entry := range breakdown {
			fmt.Fprintf(w, "  %-20s %4d (%5.1f%%)\n", entry.ToolName, entry.Count, entry.Percentage)
		}
	} else {
		fmt.Fprintln(w, "\nNo tool usage recorded today.")
	}

	return nil
}

// ---------------------------------------------------------------------------
// diff command
// ---------------------------------------------------------------------------

func newDiffCmd() *cobra.Command {
	var dataDir string

	cmd := &cobra.Command{
		Use:   "diff <from-ref> <to-ref>",
		Short: "Show Dolt data changes between commits",
		Long:  "Compares two Dolt refs (commit hashes, branches, tags) and shows table-level differences.",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runDiff(cmd, args[0], args[1], dataDir)
		},
	}

	cmd.Flags().StringVar(&dataDir, "data-dir", "", "Dolt data directory (defaults to ~/.hookwise/dolt)")
	return cmd
}

func runDiff(cmd *cobra.Command, fromRef, toRef, dataDir string) error {
	db, err := analytics.Open(dataDir)
	if err != nil {
		return fmt.Errorf("failed to open Dolt DB: %w", err)
	}
	defer db.Close()

	ctx := context.Background()
	entries, err := db.Diff(ctx, fromRef, toRef)
	if err != nil {
		return fmt.Errorf("diff failed: %w", err)
	}

	w := cmd.OutOrStdout()
	fmt.Fprintf(w, "hookwise diff %s..%s\n", fromRef, toRef)
	fmt.Fprintln(w, strings.Repeat("-", 40))

	if len(entries) == 0 {
		fmt.Fprintln(w, "No differences found.")
		return nil
	}

	for _, e := range entries {
		dataChange, _ := e.RowData["data_change"].(bool)
		schemaChange, _ := e.RowData["schema_change"].(bool)
		var changes []string
		if dataChange {
			changes = append(changes, "data")
		}
		if schemaChange {
			changes = append(changes, "schema")
		}
		changeStr := strings.Join(changes, ", ")
		if changeStr == "" {
			changeStr = "-"
		}
		fmt.Fprintf(w, "  %-8s  %-25s  changes: %s\n", e.DiffType, e.TableName, changeStr)
	}

	return nil
}

// ---------------------------------------------------------------------------
// log command
// ---------------------------------------------------------------------------

func newLogCmd() *cobra.Command {
	var (
		dataDir string
		limit   int
	)

	cmd := &cobra.Command{
		Use:   "log",
		Short: "Show Dolt commit history",
		Long:  "Displays recent Dolt commits from the hookwise analytics database.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runLog(cmd, dataDir, limit)
		},
	}

	cmd.Flags().StringVar(&dataDir, "data-dir", "", "Dolt data directory (defaults to ~/.hookwise/dolt)")
	cmd.Flags().IntVar(&limit, "limit", 10, "Maximum number of commits to show")
	return cmd
}

func runLog(cmd *cobra.Command, dataDir string, limit int) error {
	db, err := analytics.Open(dataDir)
	if err != nil {
		return fmt.Errorf("failed to open Dolt DB: %w", err)
	}
	defer db.Close()

	ctx := context.Background()
	entries, err := db.Log(ctx, limit)
	if err != nil {
		return fmt.Errorf("log query failed: %w", err)
	}

	w := cmd.OutOrStdout()
	fmt.Fprintln(w, "hookwise log")
	fmt.Fprintln(w, strings.Repeat("-", 40))

	if len(entries) == 0 {
		fmt.Fprintln(w, "No commits found.")
		return nil
	}

	for _, e := range entries {
		dateStr := e.Date.Format("2006-01-02 15:04:05")
		fmt.Fprintf(w, "%s  %s  %s\n", e.CommitHash[:minInt(7, len(e.CommitHash))], dateStr, e.Message)
	}

	return nil
}

func minInt(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// ---------------------------------------------------------------------------
// upgrade command (Batch 10 — Data Migration)
// ---------------------------------------------------------------------------

func newUpgradeCmd() *cobra.Command {
	var (
		dryRun     bool
		dataDir    string
		projectDir string
	)

	cmd := &cobra.Command{
		Use:   "upgrade",
		Short: "Migrate data from TypeScript hookwise installation",
		Long: `Detects an existing TypeScript hookwise installation (~/.hookwise/analytics.db
and ~/.hookwise/state/cost-state.json), imports the data into the Go Dolt
database, and validates config parity.

Use --dry-run to preview what would be migrated without making changes.
Original files are never modified (non-destructive).`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if projectDir == "" {
				var err error
				projectDir, err = os.Getwd()
				if err != nil {
					projectDir = "."
				}
			}

			result := migration.Run(migration.MigrationOpts{
				DryRun:      dryRun,
				DoltDataDir: dataDir,
				ProjectDir:  projectDir,
				Writer:      cmd.OutOrStdout(),
			})

			if len(result.Errors) > 0 {
				return fmt.Errorf("migration completed with %d error(s)", len(result.Errors))
			}
			return nil
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Preview migration without making changes")
	cmd.Flags().StringVar(&dataDir, "data-dir", "", "Dolt data directory (defaults to ~/.hookwise/dolt)")
	cmd.Flags().StringVar(&projectDir, "project-dir", "", "Project directory for config validation (defaults to cwd)")

	return cmd
}

// ---------------------------------------------------------------------------
// notifications command (Batch 14 — Notification Platform)
// ---------------------------------------------------------------------------

func newNotificationsCmd() *cobra.Command {
	var (
		dataDir string
		limit   int
	)

	cmd := &cobra.Command{
		Use:   "notifications",
		Short: "Display notification history",
		Long: `Shows recent notifications from budget, guard effectiveness, and coaching
producers. Notifications are stored in the Dolt analytics database and
surfaced via the status line or this command.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runNotifications(cmd, dataDir, limit)
		},
	}

	cmd.Flags().StringVar(&dataDir, "data-dir", "", "Dolt data directory (defaults to ~/.hookwise/dolt)")
	cmd.Flags().IntVar(&limit, "limit", 20, "Maximum number of notifications to show")

	return cmd
}

func runNotifications(cmd *cobra.Command, dataDir string, limit int) error {
	db, err := analytics.Open(dataDir)
	if err != nil {
		return fmt.Errorf("failed to open Dolt DB: %w", err)
	}
	defer db.Close()

	ctx := context.Background()
	ns := notifications.NewNotificationService(db)

	w := cmd.OutOrStdout()
	fmt.Fprintln(w, "hookwise notifications")
	fmt.Fprintln(w, strings.Repeat("-", 50))

	notifs, err := ns.List(ctx, limit)
	if err != nil {
		return fmt.Errorf("failed to list notifications: %w", err)
	}

	if len(notifs) == 0 {
		fmt.Fprintln(w, "No notifications.")
		return nil
	}

	for _, n := range notifs {
		ts := n.CreatedAt.Format("2006-01-02 15:04")
		surfaced := " "
		if n.SurfacedAt != nil {
			surfaced = "*"
		}

		fmt.Fprintf(w, "%s [%s] %-8s %-22s %s\n",
			surfaced, ts, n.Producer, n.Type, n.Content)
	}

	fmt.Fprintln(w, strings.Repeat("-", 50))
	fmt.Fprintf(w, "%d notification(s) shown.\n", len(notifs))

	// Mark all unsurfaced notifications as surfaced now that they've been displayed.
	unsurfaced, err := ns.Unsurfaced(ctx)
	if err != nil {
		return fmt.Errorf("failed to query unsurfaced: %w", err)
	}
	for _, n := range unsurfaced {
		_ = ns.MarkSurfaced(ctx, n.ID)
	}

	return nil
}
